### ISSUE TITLE
nice footprint for all esp8266

### ISSUE THREAD

**Issue by tggo** [twitchyliquid64/kcdb#2]
https://github.com/jdunmire/kicad-ESP8266/

**Comment by twitchy-jsonp** [comment]
Added to the database. Should be ingested in the next 20 minutes.

Have you used these modules? can you vouch for their correctness?

If yes, I'm happy to bump their ranking.

**Comment by twitchyliquid64** [comment]
Added to the database. Should be ingested in the next 20 minutes.

Have you used these modules? can you vouch for their correctness?

If yes, I'm happy to bump their ranking.
